stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  when: manual
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  when: manual
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  when: manual
  script:
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  when: manual
  script:
    - echo 'Deploy'
