version: '3.1'
services:
  search_engine_ui:
    hostname: search_engine_ui
    image: ingorbunovi/search_engine_ui:2.2
    environment:
      - MONGO=post_db
      - MONGO_PORT=27017
#        EXCLUDE_URLS=${EXCLUDE_URLS}
    ports:
      - "80:8000"
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:

