version: '3'
services:
  post_db:
    hostname: post_db
    image: mongo:${MONGO_VERSION}
    container_name: mongodb-service
    volumes:
      - post_db:/data/db
#    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - backend
    ports:
      - "27017:27017"
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq-service
    image: rabbitmq:${RABBITMQ_VERSION}
    #    volumes:
    # - rabbitmq:/var/lib/rabbitmq
    networks:
      - backend
    ports:
      - "8080:15672"
      - "5672:5672"

  prometheus:
    image: ${USER_NAME}/prometheus:1.0
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - backend
      - frontend

volumes:
  post_db:
  rabbitmq:
  prometheus_data:

networks:
  frontend:
  backend:
