---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'search_engine_ui'
    static_configs:
      - targets:
        - 'search_engine_ui:8000'

  - job_name: 'search_engine_crawler'
    static_configs:
      - targets:
        - 'search_engine_crawler:8000'
    metrics_path: /

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'

  - job_name: 'mongodb'
    static_configs:
      - targets:
        - 'mongodb-exporter:9216'
rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
          
