- name: Swarm Init
  docker_swarm:
    state: present
  become: yes

- name: Get Worker Token
  command: docker swarm join-token worker -q
  register: worker_token

- name: Show Worker Token
  debug: var=worker_token.stdout

- name: Manager Token
  command: docker swarm join-token manager -q
  register: manager_token

- name: Show Manger Token
  debug: var=manager_token.stdout

- name: Create directory for repo
  file:
    path: /otus
    state: directory
    mode: '0755'
  become: yes

- name: Clone repo
  git:
    repo: https://github.com/NickVG/Otus_Project_082019.git
    dest: /otus
  become: yes

